[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = { version = "0.5", features = ["pem", "alloc"] }
rand = "0.8"
clap = "3.0"
pkcs1 = "0.7.1"
pkcs8 = "0.10.1"